### ISSUE TITLE
Improvements to correlation

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#201]
- [x] Explore if it's possible to do without lon/lat looping in Python
- [x] Change return type for a single correlation.
- [x] Single timeseries broadcasting, see #262 
- [x] Make the operation polymorphic, see #232 
- [x] Sanity checks, see #238

**Comment by JanisGailis** [comment]
Not possible to implement the Cate monitor in a straightforward way for an operation that doesn't loop or work on group-by objects. See #282

**Comment by JanisGailis** [comment]
Sanity checks for 'None' values has been implemented through #238, other explicit checks for data validity have also been implemented.
