### ISSUE TITLE
A uniform method of adjusting global attributes of altered datasets

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-core#294]
### Expected behavior

Some operations, such as ```subset_spatial```, ```subset_temporal```, ```coregistration```, have a potential of changing dataset properties that should be properly reflected in the global attributes of affected datasets. There should be a uniform method of addressing this.

### Actual behavior

Logic that handles updates to global attributes is part of particular operations.

### Implementation hints

Create utility functions in ```ops/normalize.py``` or ```ops/utility.py``` that hamdle this. Such as ```adjust_spatial_attrs```, ```adjust_temporal_attrs``` that work with attributes denoted in [Attribute Convention for Data Discovery](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery). Specifically:

```shell
Spatial:
geospatial_lat_min:         -90.0
geospatial_lat_max:         90.0
geospatial_lon_min:         -180.0
geospatial_lon_max:         180.0
geospatial_vertical_min:    0.0
geospatial_vertical_max:    0.0
spatial_resolution:         1km at Equator
geospatial_lat_units:       degrees_north
geospatial_lon_units:       degrees_east
geospatial_lat_resolution:  0.5
geospatial_lon_resolution:  0.5

Temporal:
time_coverage_start:        20010101T000000Z
time_coverage_end:          20010101T235959Z
time_coverage_duration:     P1D
time_coverage_resolution:   P1D
```

As global attributes are optional, it is better to have no attribute than to have a wrong attribute.

### Task list
- [x] Create ```adjust_spatial_attrs```
- [x] Create ```adjust_temporal_attrs```
- [x] Use in ```subset_spatial```
- [x] Use in ```subset_temporal```
- [x] Use in ```coregistration```
- [x] Check if has to be used in other operations
- [x] Update operation development guide
- [x] Update CHANGE.md

### Specifications 
Cate 0.9.0dev3

**Comment by JanisGailis** [comment]
See also #223

**Comment by JanisGailis** [comment]
- [ ] Create ```adjust_spatial_attrs```
- [ ] Create ```adjust_temporal_attrs```
- [ ] Use in ```subset_spatial```
- [ ] Use in ```subset_temporal```
- [ ] Use in ```coregistration```
- [ ] Check if has to be used in other operations
